title:            "Ava's Keycap Space"
description:      "Making and collecting artisan keycaps."
baseurl: "" # the subpath of your site, e.g. /blog
url:              "https://www.avalai.ca"
remote_theme:     andrewbanchich/forty-jekyll-theme
permalink: pretty
# theme: forty_jekyll_theme
email: caps@avalai.ca
author: Avalai
street_address: 
city: Ottawa
state: 
zip_code: 
country: Canada
phone:

 # homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url:
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/Avalai
linkedin_url: 
pinterest_url:
slack_url:
# twitter_url: https://twitter.com/Avalai
flickr_url: https://www.flickr.com/photos/avalai/
geekhack_url: https://geekhack.org/index.php?action=profile;u=59262
discord_url: http://discord.gg/mechkeys
discord_un: "@Avalai#4780"

# build settings
markdown: kramdown

sass:
  style: compact
  sass_dir: _sass

collections:
  - keycaps
  - catalogue